
# EXERCICE 1
ex1: ex1.o
	gcc -o ex1 ex1.o

ex1.o: ex1.c
	gcc -c ex1.c


# EXERCICE 2
ex2: ex2.o
	gcc -o ex2 ex2.o

ex2.o: ex2.c
	gcc -c ex2.c


# EXERCICE 3
ex3: ex3.o
	gcc -o ex3 ex3.o

ex3.o: ex3.c
	gcc -c ex3.c


# EXERCICE 4
ex4: ex4.o
	gcc -o ex4 ex4.o

ex4.o: ex4.c
	gcc -c ex4.c


# CLEAN
clean:
	rm -f *.o ex1 ex2 ex3 ex4