FROM debian:latest
LABEL maintainer="Yoda"

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -y \
  && apt-get install -y --no-install-recommends \
  evince

RUN rm -rf /var/lib/apt/lists/*

CMD ["ls", "/"]
