#variables:
#  DOCKER_HOST: tcp://docker:2375/
#  DOCKER_DRIVER: overlay2
#  # See https://github.com/docker-library/docker/pull/166
#  DOCKER_TLS_CERTDIR: ""
#
# Official docker compose image.
#image:
#  name: docker/compose:latest
#
#services:
#    - name: docker:dind
#      entrypoint: ["env", "-u", "DOCKER_HOST"]
#      command: ["dockerd-entrypoint.sh"]
#
##build:cache:
##  stage: build
##  script:
##    - cd ./cache/
##    - docker-compose up

build:test:
  image: node:latest
  script:
    - npm install
    - npm run test
