- name: h1 config
  hosts: h1
  become: yes
  vars:
    - h_addr: 10.0.1.2
    - subnet: 10.0.3.0/24
    - r1_addr: 10.0.1.1
  tasks:
    - name: interface eth1 config
      template:
        src: templates/h_eth1.template
        dest: /etc/network/interfaces.d/eth1
    - name: reload config
      service: 
        name: networking
        state: restarted
  roles:
    - role: curl
      tags: curl_deploy