
.PHONY: main1 main2 main3 main4 main5 main6

all: main1 main2 main3 main4 main5 main6 

main1:
	gcc -m32 -fno-stack-protector -o main1 main1.c

main2:
	gcc -m32 -fno-stack-protector -o main2 main2.c -lm

main3:
	gcc -m32 -fno-stack-protector -o main3 main3.c

main4:
	gcc -m32 -fno-stack-protector -o main4 main4.c

main5:
	gcc -m32 -fno-stack-protector -o main5 main5.c

main6:
	gcc -m32 -fno-stack-protector -o main6 main6.c

