
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Nov 10 19:22:33 CET 2020
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int VRG = 9;
  public static final int PG = 7;
  public static final int PD = 8;
  public static final int EOF = 0;
  public static final int ADD = 3;
  public static final int SUB = 4;
  public static final int DIV = 6;
  public static final int ID = 2;
  public static final int error = 1;
  public static final int MUL = 5;
}

