apiVersion: v1
kind: Service
metadata:
  labels:
    component: redis
  name: redis-svc
spec:
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  selector:
    app: todo
    component: redis
  type: ClusterIP