version: "3.1"
services:
    web:
        image: nginx:alpine
        volumes:
         - ./labo3:/usr/share/nginx/html
        ports:
         - "8080:80"
        environment:
         - NGINX_HOST=nginx-visnum.com
         - NGINX_PORT=80
    #fastapi:
    #    build: ./
    #    volumes:
    #     - ./labo3/labo3:/labo3/labo3
    #    ports:
    #     - 8000:80