
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jan 27 14:00:42 CET 2021
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 28;
  public static final int TBOOLEAN = 42;
  public static final int EQUALS = 29;
  public static final int CLOSEPARENT = 7;
  public static final int PRG = 2;
  public static final int FOR = 19;
  public static final int MINUS = 26;
  public static final int WRITE = 11;
  public static final int STRINGCONST = 40;
  public static final int NOT = 38;
  public static final int TILDA = 37;
  public static final int AND = 35;
  public static final int SEMICOLON = 5;
  public static final int OR = 36;
  public static final int INF = 31;
  public static final int INTEGERCONST = 44;
  public static final int COMMA = 8;
  public static final int ENDPRG = 4;
  public static final int ENDFOR = 22;
  public static final int PLUS = 25;
  public static final int IF = 12;
  public static final int ENDWHILE = 18;
  public static final int EOF = 0;
  public static final int STARTPRG = 3;
  public static final int SUPEQUAL = 34;
  public static final int EQUAL = 9;
  public static final int TRUE = 23;
  public static final int error = 1;
  public static final int INFEQUAL = 32;
  public static final int CONSTANT = 43;
  public static final int IDENT = 39;
  public static final int FROM = 20;
  public static final int TIMES = 27;
  public static final int ENDIF = 15;
  public static final int ELSE = 14;
  public static final int TINTEGER = 41;
  public static final int READ = 10;
  public static final int TO = 21;
  public static final int WHILE = 16;
  public static final int THEN = 13;
  public static final int SUP = 33;
  public static final int DIFF = 30;
  public static final int OPENPARENT = 6;
  public static final int FALSE = 24;
  public static final int DO = 17;
}

